name: Deploy
run-name: Deploy commit ${{github.sha}}
on:
  push:
    branches:
      - main
    paths:
      - '_site/index.html'
      - '_site/styles.css'
      - '_site/functions.js'
      - 'scripts/generate_local_version.sh'
      - '.github/workflows/deploy.yml'
jobs:
  deploy:
    permissions:
      contents: write
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{steps.deploy_pages.outputs.page_url}}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Generate Single File
        id: generate_single_file
        run: ./scripts/generate_local_version.sh
      - name: Upload Artifact
        id: upload_pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site
      - name: Deploy GitHubPage
        id: deploy_pages
        uses: actions/deploy-pages@v4
